export const types = {
  SET_CITY: 'SET_CITY',
  SET_REQUEST_CITY: 'SET_REQUEST_CITY',
  GET_WEATHER: 'GET_WEATHER',
  SET_WEATHER: 'SET_WEATHER',
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  SET_INPUT_ERROR: 'SET_INPUT_ERROR',
  CLEAR_INPUT_ERROR: 'CLEAR_INPUT_ERROR',
  IS_FETCHING: 'IS_FETCHING',
}